---

- hosts: all
  become: true
  pre_tasks:


  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"



- hosts: Server1
  become: true
  tasks:
    - name: copy the pcap file
      fetch:
        src: traffic.pcap
        dest: "/home/rausan/CPE243_ausan/PCAP/"

    - block:
      - name: Authentication of extraction
        shell: cat traffic.pcap
        register: traffic

    - debug:
        msg="{{traffic}}"
